stages:
  - lint
  - test
  - notification

tslint:
  stage: lint
  script:
    - sh ./bin/tslint.sh

test:
  stage: test
  script:
    - sh ./bin/test.sh

send_change_log:
  stage: notification
  script:
    - gulp ts
    - node ./lib/js/src/tools/sendchangelog.js


